#pragma once

#include <linux/version.h>

#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 7, 0)
#define PERFCPP_NO_RECORD_CGROUP
#define PERFCPP_NO_SAMPLE_CGROUP
#endif

#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 11, 0)
#define PERFCPP_NO_SAMPLE_DATA_PAGE_SIZE
#define PERFCPP_NO_SAMPLE_CODE_PAGE_SIZE
#endif

#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 12, 0)
#define PERFCPP_NO_SAMPLE_WEIGHT_STRUCT
#endif

#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 13, 0)
#define PERFCPP_NO_CGROUP_SWITCHES
#endif